### ISSUE TITLE
Muuttujiin sijoittaminen?

### ISSUE THREAD

**Issue by henrikingo** [koodikirja/koodikirja#2]
Moikka

Tehtiin tyttären kanssa tuo Luku 1 eilen, kun Koodikirja.fi löytyi summamutikasta. Sitten vasta huomattiin, että Luku 2 on kirjoittamatta. No, tein forkin ja rupesin kirjoittamaan lukua muuttujista.

Olen toistaiseksi oppinut, että roy-kieli kyllä tukee funktioiden argumentteja. Sillähän voi jo tehdä kaikkea hauskaa. Mutta en ole löytänyt mitään tapaa oikeasti käyttää muuttujia, esim niin, että olemassaolevaan muuttujaan voisi sijoittaa uuden arvon.

Siis vaikka näin:
let kaari kulma = s [ fd 10, rt kulma, fd 10, kulma = kulma/2, rt kulma, fd 5, kulma = kulma/2, fd 5, ...]

No mikään yhtäsuuruusmerkkihän ei toimi. Onko tää Roy-kieli jotenkin jäänyt tekijöiltään kesken, vai onko tuohon siis olemassa joku ratkaisu, jota en ymmärrä? Jos muuttujia ei käytännössä voi kielessä käyttää, niin oliko tällainen rajoittuneisuus tietoinen valinta Turtle Roy ympäristöä kehitettäessä?

Mulla olisi muuten jo vähän materiaalia valmiina, mutta nyt tuntuu, etten ymmärrä miksi edes opiskella ohjelmointikieltä, jossa ei voi käyttää muuttujia? Tuntuu että teillä on ollut joku suunnitelma tässä, enkä itse ole siitä perillä?

**Comment by henrikingo** [comment]
Toinen kysymys vähän samassa hengessä: Onkos roy:ssa mitään input funktioita? Eli voiko käyttäjältää pyytää tekstiä syötteeksi, tai vaikka painella nuolinäppäimiä?

**Comment by raimohanska** [comment]
Hienoa kuulla, että olet innostunut kirjoittamaan toista lukua!

Royssa ei todellakaan ole muuttujia, vaan se on "puhdas funktionaalinen kieli". Useissa tapauksissa muuttujien käytön voi korvata rekursiolla. Esimerkiksi

```haskell
let kaari kulma = s [fd 10, rt kulma, 
  if kulma > 1 
    then kaari (kulma / 2) 
    else s []]
```

Roy-kieli ja Turtle Roy -ympäristö ovat toki rajoittuneita, eivätkä sovellu sellaisenaan esimerkiksi peliohjelmointiin. Valitsin Roy-kielen tähän oppimisympäristöön koska sillä on yksinkertainen Logoa (ja vielä enemmän Haskellia) muistuttava syntaksi ja toisaalta siksi, että Roy-kääntäjä on kirjoitettu Javascriptillä ja siten toimii selaimessa ilman tarvetta serveripuolen toiminnalisuudelle.

Muuttujatuen voi toki rakentaa helposti Javascriptillä. Ensin lisätään pari funktiota selaimen konsolissa:

```javascript
document.querySelector("iframe").contentWindow.set = function(key, value) { window.set[key] = value }
document.querySelector("iframe").contentWindow.get = function(key) { return window.set[key] }
```

Näihin funktioihin `set` ja `get` voidaan nyt viitata Turtle Roysta. Esimerkiksi:

```haskell
set "x" 50
fd (get "x")
set "kulma" 45
rt (get "kulma")
```

Input-funktion suhteen tilanne on sama: ei ole, mutta voidaan rakentaa.

**Comment by raimohanska** [comment]
Ai niin, Turtle Royssa voi myös syöttää suoraan javascriptiä:

```
λ> :js
Javascript mode!
λ> set1 = function(key, value) { window.set[key] = value }
λ> get1 = function(key) { return window.set[key] }
λ> :roy
Roy mode!
λ> set1 "x" 100
λ> get1 "x"
100
```

**Comment by raimohanska** [comment]
Jos haluaisi voida käsitellä käyttäjän tekstisyötettä, niin kannattaisi varmaan integroitua `royrepl.js` -fileessä määriteltyyn repliin. Vois ehkä ajatella että se toimisi näin:

λ> let moi nimi = print "moi " ++ nimi
λ> input "Kerro nimesi" moi
Kerro nimesi> juha
"moi juha"

Mutta toi tosiaan pitäis toteuttaa. Ei oo varmaan kummonen homma mut nyt pitää mennä saunaan!

**Comment by henrikingo** [comment]
Kiitos! Ajattelinkin, että tuo lambda-merkki voisikin olla vinkki tähän suuntaan. Itse en aikanaan ollut 100% tietotekniikan opiskelija, joten vältin pakollliset scheme-kurssit. Wikipedian lueskelu eilen illalla auttoi vähän.

Nyt kun tiedän, että roy:ssa on tosiaan tarkoituskin, että kaikki muuttujat ovat aina funktion argumentteja, niin sillä tiedolla saan kyllä jotain kohta valmiiksi. Myös käyttäjätestaus kuusivuotiaalla tuotti jo listan korjattavaa.

Mielestäni on hyvä valinta käyttää kieltä joka toimii puhtaasti selaimessa! Vaikka ymmärrän, että yliopiston CS -kursseilla funktionaalisilla kielillä on oma pointtinsa, en välttämättä näe itseisarvona, että sitä suuntausta pitäisi sen kummemmin pienille lapsille opettaa. Vähintäänkin tuo input funktio voisi olla hyödyllinen, ja miksei get-set funktiot myös.

Nyt kun muistelen omia logo-opintojani yläasteella, niin sekin oli hyvä toiminto, että pystyi lukemaan kilpikonnan sijainnin. Sillä pystyi jo tekemään pelejä, joissa kilppari muuttaa suuntaa esim törmättyään piirrosalueen reunaan.

Jos haluan joskus laajentaa turtle roy:ta esim juuri noilla get/set-funktioilla, niin ilmeisesti `turtle.js` ja `turtle.roy` tiedostot ovat oikeat sijoituspaikat? Jos laitan joskus merge-requesteja, miten suhtaudut niihin? (Lähitulevaisuudessa fokus on kuitenkin Luvun 2 kirjoittamisessa.)

**Comment by raimohanska** [comment]
Pull requestit ovat tervetulleita ja autan ihan mielelläni näissä jutuissa. Konnan sijainti on varmasti helppo toteuttaa.

Turtle.js on javascript API kilpparigrafiikkaan ja turtle.roy on sen päällä ohut roy-wrapperi.

**Comment by raimohanska** [comment]
Kiitos vielä tsempistä! Itsekin innostuin kirjoittamaan lisää. Tällä kertaa musiikista. 

https://github.com/koodikirja/koodikirja/blob/master/content/musiikkia.md

Kommentteja otetaan vastaan!
